### ISSUE TITLE
我在Kali Linux中测试，显示已应答DNS超时

### ISSUE THREAD

**Issue by Lay0us1** [b0bac/ApolloScanner#2]
The resolution lifetime expired after 5.419510841369629 seconds: Server 192.168.183.2 UDP port 53 answered The DNS operation timed out.; Server 192.168.183.2 UDP port 53 answered The DNS operation timed out.; Server 192.168.183.2 UDP port 53 answered The DNS operation timed out.
The resolution lifetime expired after 5.440458536148071 seconds: Server 192.168.183.2 UDP port 53 answered The DNS operation timed out.; Server 192.168.183.2 UDP port 53 answered The DNS operation timed out.; Server 192.168.183.2 UDP port 53 answered The DNS operation timed out.

**Comment by b0bac** [comment]
目前测试过mac和ubuntu 没有问题，kali不清楚问题，目测你的服务没起来

**Comment by b0bac** [comment]
<img width="1193" alt="图片" src="https://user-images.githubusercontent.com/11972644/158820514-fb4bdc0b-2ee1-4684-9e4d-92b409184892.png">
<img width="1786" alt="图片" src="https://user-images.githubusercontent.com/11972644/158820590-b134017f-3555-48c8-8636-8852ad3bd8ca.png">

**Comment by Lay0us1** [comment]
我再试试
