### ISSUE TITLE
window环境中报错

### ISSUE THREAD

**Issue by zs198945** [b0bac/ApolloScanner#3]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build backports.zoneinfo cryptography
ERROR: Could not build wheels for backports.zoneinfo, cryptography, which is required to install pyproject.toml-based projects
但是c++ 14.0已经装了

**Comment by b0bac** [comment]
不好意思，我们没有考虑Windows环境部署，目前仅确保支持部署在Ubuntu服务器或者MacOS上。

**Comment by zs198945** [comment]
谢谢楼主
