### ISSUE TITLE
师傅您好，以下问题烦请看看

### ISSUE THREAD

**Issue by 98Kstar** [b0bac/ApolloScanner#7]
试了两台服务器 unbunt18的，均报错以下内容
root@10-31-23-192:/home/ubuntu/ApolloScanner# pip3 install -r requirments.txt 
Collecting aiohttp==3.8.1 (from -r requirments.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /simple/aiohttp/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /simple/aiohttp/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /simple/aiohttp/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /simple/aiohttp/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)': /simple/aiohttp/
  Could not fetch URL https://pypi.internal-mirrors.ucloud.cn/simple/aiohttp/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.internal-mirrors.ucloud.cn', port=443): Max retries exceeded with url: /simple/aiohttp/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) - skipping
  Could not find a version that satisfies the requirement aiohttp==3.8.1 (from -r requirments.txt (line 1)) (from versions: )
No matching distribution found for aiohttp==3.8.1 (from -r requirments.txt (line 1))

**Comment by b0bac** [comment]
哭了，大哥，您这下载依赖库的PIP源有问题，您给我提ISSUE，我能咋办，您换个PIP源不就完了吗，另外结合您的系统换个版本啥的。
