### ISSUE TITLE
path路径遍历的时候 请问是否进行里 agent的伪造呢？

### ISSUE THREAD

**Issue by 494645654** [b0bac/ApolloScanner#9]

**Comment by 494645654** [comment]
另外 字典这块还需要补充吧。  目前username 和password 太少里

**Comment by 494645654** [comment]
1、安装的时候 mysql配置账号 根据 ApolloScanner文件夹下setting文件  需要配置  用户名 root，密码root        使用说明中都没有说明。对于我这种小白自己摸索里半天。
2、 终端runserver后 直接关闭。进程依旧运行问题 如何解决。  kill pid后 访问8000端口 依旧生成新的pid。

**Comment by b0bac** [comment]
对于第二个问题，可以详细描述下，并给出一些报错的现象，便于修改。

**Comment by 494645654** [comment]
![image](https://user-images.githubusercontent.com/34673490/159885187-8cd4eec9-1743-4f05-8b71-220d6b49991a.png)

**Comment by b0bac** [comment]
原有的进程应该是没有杀掉，导致端口被占用，可以切换一个端口启动。

**Comment by b0bac** [comment]
p.s. oh my zsh 的agnoster主题可以通过安装melso字体修复乱码问题。

**Comment by 494645654** [comment]
miaodewei@miudeweideMacBook-Pro  ~/scantools/ApolloScanner-master  lsof -i tcp:8000
COMMAND   PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    886 miaodewei   39u  IPv4 0x42d21705859b3c35      0t0  TCP localhost:49537->localhost:irdmi (ESTABLISHED)
 miaodewei@miudeweideMacBook-Pro  ~/scantools/ApolloScanner-master  kill -9 886
 miaodewei@miudeweideMacBook-Pro  ~/scantools/ApolloScanner-master  sudo python3 manage.py runserver
Watching for file changes with StatReloader
[2022-03-24 17:29:18,345] [INFO] [autoreload.py 20 line] Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

System check identified 1 issue (0 silenced).
March 24, 2022 - 17:29:18
Django version 4.0.1, using settings 'ApolloScanner.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
 ✘ miaodewei@miudeweideMacBook-Pro  ~/scantools/ApolloScanner-master  kill -9 886
kill: kill 886 failed: no such process
 ✘ miaodewei@miudeweideMacBook-Pro  ~/scantools/ApolloScanner-master  lsof -i tcp:8000
 ✘ miaodewei@miudeweideMacBook-Pro  ~/scantools/ApolloScanner-master  lsof -i tcp:8000
COMMAND     PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    10399 miaodewei   26u  IPv4 0x42d2170588ef064d      0t0  TCP localhost:52968->localhost:irdmi (ESTABLISHED)
Google    10399 miaodewei   28u  IPv4 0x42d2170588eee495      0t0  TCP localhost:52969->localhost:irdmi (ESTABLISHED)

**Comment by 494645654** [comment]
![image](https://user-images.githubusercontent.com/34673490/159886106-d6eb55e1-e4d6-438d-b179-be4ff6ae9121.png)

**Comment by b0bac** [comment]
1.一般等一会以后在测试是否有问题，可能是进程清理的慢！这块是由django框架实现的功能。
2.如果需要尽快调试的话，可以修改启动端口例如 python3 manage.py runserver 8080

**Comment by 494645654** [comment]
python3 manage.py runserver 8080 直接关闭iterm终端。依旧 未真正关闭进程

**Comment by 494645654** [comment]
且同时 8080 和9000 都可以使用

**Comment by b0bac** [comment]
这说明进程没有关闭 建议使用 ps aux | grep python 进行查看，使用sudo kill -9 pid 杀掉进程

**Comment by 494645654** [comment]
感谢 进程问题已经解决
